"""empty message

Revision ID: 7234b82da91d
Revises: b27ec87c8f5e
Create Date: 2017-11-06 08:34:03.202544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7234b82da91d'
down_revision = 'b27ec87c8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('image_tag', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_image')
    # ### end Alembic commands ###
