version: "3"
services:

    nginx:
        restart: always
        image: nginx:alpine
        ports:
          - "80:80"
#          - "443:443"
        volumes:
#          - ./www/:/var/www/html/:rw
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
          - ./nginx/conf.d/:/etc/nginx/conf.d/:rw          
          - ./log/nginx/:/var/log/nginx/:rw
        links:
          - flask-uwsgi:flask-uwsgi

    flask-uwsgi:
        restart: always
        build: ./app/
        expose:
          - "5000"
        volumes:
#          - ./www/:/var/www/html/:rw
#          - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
#          挂载应用程序目录
          - ./app/my_blog/:/app/my_blog/:rw   
          - ./log/flask-uwsgi/:/var/log/flask-uwsgi/:rw
        depends_on:
          - mysql
        links:
          - mysql:mysql

    mysql:
        restart: always
        build: ./mysql/
        ports:
          - "3306:3306"
        volumes:
#          - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
          - ./mysql/DB/:/var/lib/mysql/:rw
          - ./log/mysql/:/var/log/mysql/:rw
        environment:
          - MYSQL_ROOT_PASSWORD=Mx560205
